[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pyright]
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnusedImport = true
reportUnusedVariable = true
reportUnusedClass = true
reportUnusedFunction = true
reportImportCycles = true
reportOptionalMemberAccess = true
reportUntypedBaseClass = true
reportPrivateUsage = true
reportConstantRedefinition = true
reportInvalidStringEscapeSequence = true
reportUnnecessaryIsInstance = true
reportUnnecessaryCast = true
reportAssertAlwaysTrue = true
reportSelfClsParameterName = true
